[project]
name = "micrograd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shan", email = "shan.ali.ru@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
]

[project.scripts]
micrograd = "micrograd:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]
